### ISSUE TITLE
Clarify topics for collaborators

### ISSUE THREAD

**Issue by der-bruemmer** [hdaSprachtechnologie/odenet#3]
Can you clarify how to contribute to the project? Maybe open a few issues external collaborators can pull?

What's the relation to the Open Multilingual Wordnet? Could sources like Wiktionary/DBnary or BabelNet be integrated? Are there guidelines for the review of synsets?

**Comment by fcbond** [comment]
G'day,

Can you clarify how to contribute to the project? Maybe open a few issues
> external collaborators can pull?
>
I think manual verification of lemmas --- these German words/definition
fits this synset is probably the most pressing task.   I am not sure what
we have in the way of guidelines.

What's the relation to the Open Multilingual Wordnet? Could sources like
> Wiktionary/DBnary or BabelNet be integrated? Are there guidelines for the
> review of synsets?
>

One of the goals of this project is to make German part of the Open
Multilingual Wordnet, and it has used the automatically constructed
Wiktionary mappings from the Extended OMW.  We can't use BabelNet due to
its license, but DBnary should be fine.

-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by fcbond** [comment]
Hi,

@goodmami has created a new python interface to the LMF formatted wordnets, similar to the existing NLTK interface, which you might be interested in: https://github.com/goodmami/wn/  It is not so well documented yet, but the code is clean :-).  So far it has been tested mainly on the English Wordnet, and is now being tested on Odenet.

Yours,

**Comment by hdaSprachtechnologie** [comment]
Contributions are highly appreciated. At the current state, we need to add information (like German definitions and more relations) and correct information (such as ili links). The jupyter notebook "Arbeiten_mit_OdeNet.ipynb" gives some interfaces to support this process. The best would be to write me an email (melanie.siegel@h-da.de), such that we can directly communicate about the best way. 

Best,
Melanie
