### ISSUE TITLE
Please add basic installation / usage example in README

### ISSUE THREAD

**Issue by bionicles** [hdaSprachtechnologie/odenet#7]
Would it please be possible to add a few code blocks in the README file to show how to install this and use it? The ipynb files don't always load correctly, and that could help more people contribute to the project! 

Thanks so much for making this by the way...amazing to me that "open multilingual wordnet" doesn't have critical languages like  German!

**Comment by fcbond** [comment]
Hi,

> Would it please be possible to add a few code blocks in the README file to
> show how to install this and use it? The ipynb files don't always load
> correctly, and that could help more people contribute to the project!
>
you can install the OMW software locally and use it to access it <
https://github.com/globalwordnet/OMW>.   We are also working on a new nltk
interface, but it is not ready yet.


> Thanks so much for making this by the way...amazing to me that "open
> multilingual wordnet" doesn't have critical languages like German!
>

We wanted German, which is why we are working with Melanie.  Unfortunately,
GermaNet is a great resource but not open, so we could not include it.

-- 
Francis 'OMW' Bond <http://www3.ntu.edu.sg/home/fcbond/>

**Comment by hdaSprachtechnologie** [comment]
OdeNet is now released on the WN module. The usage description can be found here:
https://wn.readthedocs.io/en/latest/index.html
